# Generated by Django 4.2.7 on 2023-12-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyTypes',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=30)),
                ('faculty_description', models.CharField(max_length=1500)),
                ('faculty_image_url', models.CharField(blank=True, max_length=50, null=True)),
                ('faculty_status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('login', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('role', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationForDeducation',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_application_create', models.DateField(blank=True, null=True)),
                ('date_application_accept', models.DateField(blank=True, null=True)),
                ('date_application_complete', models.DateField(blank=True, null=True)),
                ('application_status', models.TextField()),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
        ),
    ]
