# Generated by Django 4.2.6 on 2023-12-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('image_url', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('login', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('role', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationForDeducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application_create', models.DateField(blank=True, null=True)),
                ('date_application_accept', models.DateField(blank=True, null=True)),
                ('date_application_complete', models.DateField(blank=True, null=True)),
                ('application_status', models.TextField()),
                ('students', models.ManyToManyField(to='app.student')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
        ),
    ]
